led.enable(true)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P5, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P6, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P7, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P5, 0)
    pins.digitalWritePin(DigitalPin.P6, 0)
    pins.digitalWritePin(DigitalPin.P7, 0)
    basic.pause(500)
})
